# -*- coding: utf-8 -*-
"""Armstrong_Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CDWW5L2Hu2erLhtv-PevF1PmPAzJUrSj

Task:

Find out if a given number is an "Armstrong Number".

An n-digit number that is the sum of the nth powers of its digits is called an n-Armstrong number. Examples :
371 = 33 + 73 + 13;
9474 = 94 + 44 + 74 + 44;
93084 = 95 + 35 + 05 + 85 + 45.

Write a Python program that;
takes a positive integer number from the user,
checks the entered number if it is Armstrong,
consider the negative, float and any entries other than numeric values then display a warning message to the user.
"""

x = input("Please enter a positive number: ")
x_list = sorted(x)

sum = 0
while x.isnumeric():
  for i in x_list:
    sum += int(i) ** len(x_list)
  if sum == int(x):
    print(x, "is an Armstrong number")
  else:
      print(x, "is not an Armstrong number")
  break

else:
    print("It is an invalid entry. Don't use non-numeric, float, or negative values!")