AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an EC2 instance that enables SSH.  
Resources:
  Ec2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ab4d1e9cf9a1215a
      InstanceType: t2.micro
      KeyName: fatma_bakir_key
      SecurityGroups:
        - cloudformation_demo_secgrp
      Tags:
        - Key: Name
          Value: Fatma-cloudformation-demo

 
  